<?php
session_start();if(!isset($_SESSION['user'])){header('Location:../index.php');exit;}
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/permissions.php';requirePermission('audit_view');
$entity=trim($_GET['entity']??'');$user=trim($_GET['user']??'');$sql='SELECT * FROM audit_logs WHERE 1=1';$types='';$params=[];
if($entity!==''){$sql.=' AND entity_type=?';$types.='s';$params[]=$entity;}if($user!==''){$sql.=' AND username LIKE ?';$types.='s';$params[]='%'.$user.'%';}$sql.=' ORDER BY id DESC LIMIT 500';$stmt=$conn->prepare($sql);if($types)$stmt->bind_param($types,...$params);$stmt->execute();$logs=$stmt->get_result();$entities=$conn->query('SELECT DISTINCT entity_type FROM audit_logs ORDER BY entity_type');
$page_title='Audit log';require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div class="page-hero"><div><div class="page-kicker">Security</div><h1 class="page-title">Audit log</h1><p class="page-subtitle">See who created, changed, deleted, converted or reset important records.</p></div></div>
<form class="card card-body mb-3" method="get"><div class="row g-2"><div class="col-md-5"><input class="form-control" name="user" value="<?=htmlspecialchars($user);?>" placeholder="Search username"></div><div class="col-md-4"><select class="form-select" name="entity"><option value="">All record types</option><?php while($e=$entities->fetch_assoc()):?><option value="<?=htmlspecialchars($e['entity_type']);?>" <?=$entity===$e['entity_type']?'selected':'';?>><?=htmlspecialchars(ucwords(str_replace('_',' ',$e['entity_type'])));?></option><?php endwhile;?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Filter</button></div></div></form>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Date</th><th>User</th><th>Action</th><th>Record</th><th>Details</th></tr></thead><tbody><?php if(!$logs->num_rows):?><tr><td colspan="5"><div class="empty-state">No activity has been recorded yet.</div></td></tr><?php endif;?><?php while($log=$logs->fetch_assoc()):?><tr><td><?=date('d M Y H:i',strtotime($log['created_at']));?></td><td><?=htmlspecialchars($log['username']?:'System');?></td><td><span class="badge text-bg-secondary"><?=htmlspecialchars($log['action']);?></span></td><td><?=htmlspecialchars(ucwords(str_replace('_',' ',$log['entity_type'])));?><?php if($log['entity_id']!==null):?><small class="d-block text-muted">#<?=htmlspecialchars($log['entity_id']);?></small><?php endif;?></td><td><?=htmlspecialchars($log['summary']);?></td></tr><?php endwhile;?></tbody></table></div></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
