<?php
session_start();if(!isset($_SESSION['user'])){header('Location:../index.php');exit;}
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/permissions.php';require_once __DIR__.'/../includes/audit.php';requirePermission('quotations_manage');
$id=(int)($_POST['id']??0);$target=$_POST['target']??'';if($_SERVER['REQUEST_METHOD']!=='POST'||empty($_SESSION['quotation_csrf'])||!hash_equals($_SESSION['quotation_csrf'],$_POST['csrf_token']??'')||!in_array($target,['order','invoice'],true)){$_SESSION['error']='Invalid conversion request.';header('Location:view.php?id='.$id);exit;}
$conn->begin_transaction();
try{$stmt=$conn->prepare("SELECT * FROM quotations WHERE id=? AND status<>'Converted' FOR UPDATE");$stmt->bind_param('i',$id);$stmt->execute();$q=$stmt->get_result()->fetch_assoc();if(!$q)throw new Exception('Quotation is missing or already converted.');$stmt=$conn->prepare('SELECT * FROM quotation_items WHERE quotation_id=? ORDER BY id');$stmt->bind_param('i',$id);$stmt->execute();$items=$stmt->get_result();
 if($target==='order'){$status='Quotation';$stmt=$conn->prepare('INSERT INTO orders (invoice_no,customer_id,order_status,notes) VALUES (?,?,?,?)');$stmt->bind_param('siss',$q['quote_no'],$q['customer_id'],$status,$q['notes']);$stmt->execute();$newId=$conn->insert_id;$insert=$conn->prepare("INSERT INTO order_items (order_id,factory_product_id,product_name,width_mm,height_mm,width_ft,height_ft,calculation_type,quantity,sqft,description,final_price_per_sqft) VALUES (?,?,?,?,?,?,?,'SQFT',?,?,?,?)");while($i=$items->fetch_assoc()){$wf=ceil(($i['width_mm']/304.8)*2)/2;$hf=ceil(($i['height_mm']/304.8)*2)/2;$insert->bind_param('iisddddidsd',$newId,$i['factory_product_id'],$i['product_name'],$i['width_mm'],$i['height_mm'],$wf,$hf,$i['quantity'],$i['sqft'],$i['description'],$i['unit_price']);$insert->execute();}$field='order_id';$url='/orders/view.php?id='.$newId;}
 else{$seq=(int)$conn->query('SELECT COALESCE(MAX(invoice_sequence),0)+1 n FROM invoices FOR UPDATE')->fetch_assoc()['n'];$no='INV-'.date('Y').'-'.str_pad((string)$seq,6,'0',STR_PAD_LEFT);$payment='Unpaid';$status='Draft';$balance=$q['total'];$stmt=$conn->prepare('INSERT INTO invoices (customer_id,invoice_no,subtotal,discount,grand_total,deposit,balance,payment_status,invoice_status,notes,invoice_sequence) VALUES (?,?,?,?,?,0,?,?,?,?,?)');$stmt->bind_param('isddddsssi',$q['customer_id'],$no,$q['subtotal'],$q['discount'],$q['total'],$balance,$payment,$status,$q['notes'],$seq);$stmt->execute();$newId=$conn->insert_id;$insert=$conn->prepare("INSERT INTO invoice_items (invoice_id,item_type,product_name,quantity,width_mm,height_mm,sqft,price,total,description) VALUES (?,'SERVICE',?,?,?,?,?,?,?,?)");while($i=$items->fetch_assoc()){$insert->bind_param('isiddddds',$newId,$i['product_name'],$i['quantity'],$i['width_mm'],$i['height_mm'],$i['sqft'],$i['unit_price'],$i['total'],$i['description']);$insert->execute();}$field='invoice_id';$url='/invoices/view.php?id='.$newId;}
 $stmt=$conn->prepare("UPDATE quotations SET status='Converted', $field=? WHERE id=?");$stmt->bind_param('ii',$newId,$id);$stmt->execute();auditLog($conn,'CONVERT','quotation',$id,'Converted '.$q['quote_no'].' to '.$target,null,[$target.'_id'=>$newId]);$conn->commit();$_SESSION['success']='Quotation converted to '.$target.'.';header('Location:'.$url);exit;
}catch(Throwable $e){$conn->rollback();$_SESSION['error']='Conversion failed: '.$e->getMessage();header('Location:view.php?id='.$id);exit;}
