<?php
session_start();if(!isset($_SESSION['user'])){header('Location:../index.php');exit;}
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/permissions.php';requirePermission('quotations_view');
$id=(int)($_GET['id']??0);$stmt=$conn->prepare('SELECT q.*,c.name customer_name,c.phone,c.address FROM quotations q JOIN customers c ON c.id=q.customer_id WHERE q.id=?');$stmt->bind_param('i',$id);$stmt->execute();$quote=$stmt->get_result()->fetch_assoc();if(!$quote){http_response_code(404);die('Quotation not found.');}$stmt=$conn->prepare('SELECT * FROM quotation_items WHERE quotation_id=? ORDER BY id');$stmt->bind_param('i',$id);$stmt->execute();$items=$stmt->get_result();if(empty($_SESSION['quotation_csrf']))$_SESSION['quotation_csrf']=bin2hex(random_bytes(32));
$page_title=$quote['quote_no'];require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div class="page-hero"><div><h1 class="page-title"><?=htmlspecialchars($quote['quote_no']);?></h1><p class="page-subtitle"><?=htmlspecialchars($quote['customer_name']);?> · <?=date('d M Y',strtotime($quote['quote_date']));?></p></div><span class="badge text-bg-primary fs-6"><?=htmlspecialchars($quote['status']);?></span></div>
<?php if(!empty($_SESSION['success'])):?><div class="alert alert-success"><?=htmlspecialchars($_SESSION['success']);unset($_SESSION['success']);?></div><?php endif;?><?php if(!empty($_SESSION['error'])):?><div class="alert alert-danger"><?=htmlspecialchars($_SESSION['error']);unset($_SESSION['error']);?></div><?php endif;?>
<div class="card mb-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product</th><th>Dimensions</th><th class="text-end">Qty</th><th class="text-end">Sqft</th><th class="text-end">Rate</th><th class="text-end">Total</th></tr></thead><tbody><?php while($i=$items->fetch_assoc()):?><tr><td><strong><?=htmlspecialchars($i['product_name']);?></strong><?php if($i['description']):?><small class="d-block text-muted"><?=htmlspecialchars($i['description']);?></small><?php endif;?></td><td><?=number_format((float)$i['width_mm'],0);?> × <?=number_format((float)$i['height_mm'],0);?> mm</td><td class="text-end"><?=$i['quantity'];?></td><td class="text-end"><?=number_format((float)$i['sqft'],2);?></td><td class="text-end"><?=number_format((float)$i['unit_price'],2);?></td><td class="text-end fw-bold"><?=number_format((float)$i['total'],2);?></td></tr><?php endwhile;?></tbody><tfoot><tr><td colspan="5" class="text-end">Subtotal</td><td class="text-end"><?=number_format((float)$quote['subtotal'],2);?></td></tr><tr><td colspan="5" class="text-end">Discount</td><td class="text-end"><?=number_format((float)$quote['discount'],2);?></td></tr><tr><th colspan="5" class="text-end">Total</th><th class="text-end"><?=number_format((float)$quote['total'],2);?></th></tr></tfoot></table></div></div>
<?php if($quote['notes']):?><div class="card card-body mb-4"><strong class="mb-2">Notes</strong><?=nl2br(htmlspecialchars($quote['notes']));?></div><?php endif;?>
<?php if(hasPermission('quotations_manage') && $quote['status']!=='Converted'):?><div class="card card-body"><h2 class="h5">Convert quotation</h2><p class="text-muted">Create the next business document using these items and prices.</p><div class="d-flex flex-wrap gap-2"><form action="convert.php" method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['quotation_csrf']);?>"><input type="hidden" name="id" value="<?=$id;?>"><input type="hidden" name="target" value="order"><button class="btn btn-outline-primary"><i class="fa fa-clipboard-list"></i> Convert to order</button></form><form action="convert.php" method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['quotation_csrf']);?>"><input type="hidden" name="id" value="<?=$id;?>"><input type="hidden" name="target" value="invoice"><button class="btn btn-primary"><i class="fa fa-file-invoice"></i> Convert to invoice</button></form></div></div><?php endif;?>
<?php require_once __DIR__.'/../includes/footer.php';?>
